services:
  vector-websetup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-websetup
    environment:
      PORT: 7000
    ports:
      - 7000:7000
    restart: unless-stopped
